services:
  performance-insight:
    container_name: performance-insight
    build: .
    ports:
      - "7891:7891"
    volumes:
      - data:/usr/src/app/data
    environment:
      - TZ=America/Bogota

volumes:
  data: